export const paths = {
	"applicant-register": "/applicant-register",
	"user-login": "/user-login",
	home: "/jobs-news",
	"employer-register": "/employer-register",
	"job-posting": "/job-posting",
	"posted-jobs": "/posted-jobs",
	"upload-cv": "/upload-cv",
	"job-detail": "/job-detail",
	"resume-management": "/resume-management",
	"update-jobPost": "/update-jobPost",
	"job-detail-recruiter-view": "/job-detail-recruiter-view",
	"application-management": "/application-management",
	"user-profile": "/profile",
	"application-detail-recruiter-view": "/application-detail-recruiter-view",
	"applicant-job-recommendation": "/view-job-recommendations",
	"companies-hiring": "/companies-hiring",
	"admin-page": "/admin",
};
