server:
  port: 8080
  servlet:
    context-path: /jobbridge

spring:
  application:
    name: jobbridge
  datasource:
    url: jdbc:mysql://localhost:3307/jobbridge_db?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    password: guest
    port: 5672
    username: guest
    virtual-host: job
    virtual-host-job: jobbridge


jwt:
  signerKey: "2OtyvNQV2zxB/n6sueTCLbECW9HDHIbdrJlcqiHd9h2OoX7FIQN+1/jFSklXDoUI"
  valid-duration: 24 # in hours
  refreshable-duration: 120 # in hours

jobPost:
  cruiter-view-page-size: 5
  applicant-view-page-size: 12
  recommended-page-size: 4

cloudinary:
  cloud-name: "dad8ejn0r"
  api-key: "916986197549325"
  api-secret: "8ZDd8GQafg9rc9_h5UrIBt0SZ4Q"

application:
  unseen-status: "UNSEEN"
  seen-status: "SEEN"
  suitable-status: "SUITABLE"
  not-suitable-status: "NOT_SUITABLE"

spring-mail:
  mail:
    host: smtp.gmail.com
    port: 587
    username: locla2405@gmail.com
    password: mxefvqoykuezxuwz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
